### ISSUE TITLE
dxgui as a submodule

### ISSUE THREAD

**Issue by qaisjp** [JR10/mta-business#8]
Maybe having the dxgui folder work as a submodule would be better for your codebase? I'm not sure if it automatically clones it when you're downloading release zips though.

**Comment by hamdyjs** [comment]
That's exactly the problem, downloading or cloning it would simply download an empty folder. I have the folder as a repo locally, but git-ignoring 'dxgui/. git*'. This is somewhat a workaround for the submodule issue.

**Comment by qaisjp** [comment]
Fair enough
